### ISSUE TITLE
I can see your hashed passwords in sec.conf (Weechat)

### ISSUE THREAD

**Issue by melroy89** [bmeneguele/dotfiles#2]

**Comment by bmeneg** [comment]
That's not a problem. Isn't it the idea of hashed passwords? They're hashed, you can't use them directly, unless you can reverse them, but if you do so... most of the world user's are doomed, turning sha256 in an useless algorithm to be used for hashing.

**Comment by melroy89** [comment]
> That's not a problem. Isn't it the idea of hashed passwords? They're hashed, you can't use them directly, unless you can reverse them, but if you do so... most of the world user's are doomed, turning sha256 in an useless algorithm to be used for hashing.

Yes but. Even then it's not advised to share hashed passwords, with enough resources hashed passwords can be brute forced now or in the future.

**Comment by bmeneg** [comment]
That's indeed true and one of the reasons I started using integration with OpenGPG and decrypting the passwords instead of pure hash. To be honest, I haven't used Weechat for quite some time already, so I'll probably remove it from this repo. Unfortunately, the history will remain.

Anyway, thanks for the warning!
